# Network Configuration
UDP_IP = "127.0.0.1"
UDP_PORT = 5005

# Display & Debug
SHOW_PREVIEW = True
DEBUG_MODE = True
SAVE_PREVIEW = False
SAVE_PATH = "../output.mp4"

# Video source selection
USE_CAMERA = True
CAMERA_INDEX = 0
VIDEO_PATH = "../WIN_20260923_15_21_55_Pro.mp4"

# Asset Paths
MODEL_DIR = "../models_data"

# Tracker Parameters

# FACE
FACE_NUM_FACES = 1
FACE_MIN_CONFIDENCE = 0.5
FACE_BLENDSHAPES = ['jawOpen']

# Person Trackerq
PERSON_NUM_PERSONS = 2
PERSON_CONFIDENCE_THRESHOLD = 0.40
PERSON_MAX_AGE_FRAMES = 30
PERSON_MAX_COSINE_DIST = 0.20
PERSON_REID_SIMILARITY_THRESHOLD = 0.65
PERSON_DETECTOR_IMAGE_SIZE = 480
PERSON_DETECTION_FRAME_SKIP = 2

# Pose Tracker
POSE_NUM_POSES = 1
POSE_MIN_CONFIDENCE = 0.5
LANDMARK_FRAME_SKIP = 2
